# Generated by Django 5.2.4 on 2025-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=100)),
                ('full_title', models.CharField(max_length=255)),
                ('book_type', models.CharField(choices=[('theory', 'Теория'), ('exercises', 'Задачник')], max_length=20)),
                ('classes', models.CharField(max_length=50)),
                ('eras', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('djvu', 'DJVU')], max_length=10)),
                ('file_link', models.FileField(upload_to='materials/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
