# Generated by Django 5.2.4 on 2025-08-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_book_complexity_alter_book_file_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('class_levels', models.JSONField(default=list)),
                ('difficulty', models.PositiveSmallIntegerField(default=3)),
                ('theme', models.CharField(choices=[('mechanics', 'Механика'), ('electrodynamics', 'Электродинамика'), ('thermodynamics', 'Термодинамика'), ('optics', 'Оптика'), ('quantum', 'Квантовая физика')], max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='demos/icons/')),
                ('tags', models.ManyToManyField(blank=True, to='students.tag')),
            ],
        ),
    ]
