# Generated by Django 5.2.4 on 2025-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_tag_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='theme',
            field=models.CharField(choices=[('maths', 'математика'), ('mechanics', 'механика'), ('electrodynamics', 'электродинамика'), ('thermodynamics', 'термодинамика'), ('optics', 'оптика'), ('quantum', 'квантовая физика')], max_length=30),
        ),
    ]
