# Generated by Django 5.2.4 on 2025-08-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_demo_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='controls_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='script_js',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='theory_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demo',
            name='theme',
            field=models.CharField(choices=[('maths', 'Математика'), ('mechanics', 'Механика'), ('electrodynamics', 'Электродинамика'), ('thermodynamics', 'Термодинамика'), ('optics', 'оптика'), ('quantum', 'квантовая физика')], max_length=30),
        ),
    ]
