# Generated by Django 5.2.4 on 2025-08-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_demo_controls_html_demo_script_js_demo_theory_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='controls_html',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='script_js',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='theory_html',
        ),
        migrations.AddField(
            model_name='demo',
            name='controls_file',
            field=models.FileField(blank=True, null=True, upload_to='demos/controls/'),
        ),
        migrations.AddField(
            model_name='demo',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='demos/scripts/'),
        ),
        migrations.AddField(
            model_name='demo',
            name='theory_file',
            field=models.FileField(blank=True, null=True, upload_to='demos/theory/'),
        ),
    ]
