# Generated by Django 5.2.4 on 2025-08-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_demo_controls_html_remove_demo_script_js_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='controls_file',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='script_file',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='theory_file',
        ),
        migrations.AddField(
            model_name='demo',
            name='controls_template',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demo',
            name='script_static',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demo',
            name='theory_template',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
