# Generated by Django 5.2.4 on 2025-08-31 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_demo_controls_file_remove_demo_script_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('theory_id', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='students.demo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
